apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kjjebk7or-go 
  janus-idp.io/tekton: kjjebk7or-go
  backstage.io/kubernetes-id: kjjebk7or-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kjjebk7or-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  