apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kjjebk7or-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kjjebk7or-go 
  name: kjjebk7or-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kjjebk7or-go 
